steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', '${_GCP_LOCATION}-docker.pkg.dev/${_GCP_PROJECT_ID}/${_GCP_ARTIFACT_REGISTRY_REPO}/mushroom-classification-model:efficientnet-v3-001', '-f', 'image-model.dockerfile', '.' ]

- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', '${_GCP_LOCATION}-docker.pkg.dev/${_GCP_PROJECT_ID}/${_GCP_ARTIFACT_REGISTRY_REPO}/mushroom-classification-gateway:001', '-f', 'image-gateway.dockerfile', '.' ]

substitutions:
    _GCP_LOCATION: <YOUR_REPOSITORY_REGION>
    _GCP_PROJECT_ID: <YOUR_PROJECT_ID>
    _GCP_ARTIFACT_REGISTRY_REPO: mushroom-classification-repo

images:
- '${_GCP_LOCATION}-docker.pkg.dev/${_GCP_PROJECT_ID}/${_GCP_ARTIFACT_REGISTRY_REPO}/mushroom-classification-model:efficientnet-v3-001'
- '${_GCP_LOCATION}-docker.pkg.dev/${_GCP_PROJECT_ID}/${_GCP_ARTIFACT_REGISTRY_REPO}/mushroom-classification-gateway:001'