steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/mushroom-classification-repo/mushroom-classification-model:efficientnet-v3-001', '-f', 'image-model.dockerfile', '.' ]

- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/mushroom-classification-repo/mushroom-classification-gateway:001', '-f', 'image-gateway.dockerfile', '.' ]

images:
- 'us-central1-docker.pkg.dev/$PROJECT_ID/mushroom-classification-repo/mushroom-classification-model:efficientnet-v3-001'
- 'us-central1-docker.pkg.dev/$PROJECT_ID/mushroom-classification-repo/mushroom-classification-gateway:001'